import "./globals.css";

export const metadata = {
  title: "Starvell",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/fonts/inter.css" />
        <link rel="icon" href="/starvell.svg" type="image/svg+xml" />
      </head>
      <body>{children}</body>
    </html>
  );
}
