export const categories = [
  { id: "robux", name: "Робуксы", count: 395 },
  { id: "gift-cards", name: "Подарочные карты", count: 1193 },
  { id: "robux-packs", name: "Донат робуксов (паки)", count: 777 },
  { id: "premium", name: "Premium", count: 1193 },
  { id: "vip-server", name: "VIP-сервер", count: 395 },
  { id: "accounts", name: "Аккаунты", count: 1193 },
  { id: "skins", name: "Скины", count: 777 },
  { id: "prime-gaming", name: "Prime Gaming", count: 395 },
  { id: "studio", name: "Studio", count: 1193 },
  { id: "other", name: "Прочее", count: 395 },
  { id: "adopt-me", name: "Adopt Me", count: 1193 },
  { id: "anime-defenders", name: "Anime Defenders", count: 777 },
  { id: "arm-wrestle-simulator", name: "Arm Wrestle Simulator", count: 1193 },
  { id: "astd", name: "ASTD", count: 395 },
  { id: "blade-ball", name: "Blade Ball", count: 1193 },
  { id: "blox-fruits", name: "Blox Fruits", count: 777 },
  { id: "da-hood", name: "Da Hood", count: 395 },
  { id: "gpo", name: "GPO", count: 1193 },
  { id: "jailbreak", name: "Jailbreak", count: 777 },
  { id: "jujutsu-shenanigans", name: "Jujutsu Shenanigans", count: 395 },
  { id: "king-legacy", name: "King Legacy", count: 1193 },
  { id: "mm2", name: "MM2", count: 777 },
  { id: "pet-simulator-99", name: "Pet Simulator 99", count: 1193 },
  { id: "pet-simulator-x", name: "Pet Simulator X", count: 395 },
  { id: "project-slayers", name: "Project Slayers", count: 1193 },
  { id: "toilet-tower-defense", name: "Toilet Tower Defense", count: 777 },
  {
    id: "tower-defense-simulator",
    name: "Tower Defense Simulator",
    count: 395,
  },
  { id: "yba", name: "YBA", count: 1193 },
  { id: "other-games", name: "Прочие игры", count: 777 },
];

export const tabs = [
  { id: "all", label: "Все" },
  { id: "beli", label: "Бели" },
  { id: "accounts", label: "Аккаунты" },
  { id: "items", label: "Предметы" },
  { id: "vip-server", label: "VIP-сервер" },
  { id: "services", label: "Услуги" },
  { id: "guides", label: "Гайды" },
];
